---
title: "T1D_Tetramer_Cells_Analysis"
output:
  pdf_document: default
  html_document: default
---

```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
knitr::opts_knit$set(global.par = TRUE)
```

```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
library(plyr)
library(ggplot2)
library(RColorBrewer)
library(reshape2)
library(gplots)
library(gtools)
library(stats)
library(lattice)
library(latticeExtra)
library(grid)
library(gridExtra)
library(wesanderson)
library(Rtsne)
library(umap)
```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}

## set baseDir if Knitting with RStudio button
baseDir <- "~/Desktop/Su Lab/single_cell_T1D/"

## sets path if run from runAnalysis.R
#currentFile <- rstudioapi::getActiveDocumentContext()$path
#baseDir <- gsub("single_cell_T1D/.*", "single_cell_T1D/", currentFile)

#### source function scripts ####
funcDir <- paste(baseDir, "src/functions/", sep="")
funcFiles <- c("formatRaw.R", 
               "dataLoadT1D.R", 
               "cleanCt.R", 
               "geneSetEnrichment.R", 
               "violinPlot.R", 
               "heatmap2_custom.R",
               "heatmap.3.R",
               "clusterFilter.R",
               "tableBarPlots.R",
               "clusterReport.R",
               "reportViolins.R",
               "reportTSNE.R",
               "plotTSNE.R",
               "plotUMAP.R")
funcFiles <- paste(funcDir, funcFiles, sep="")
for(file in funcFiles){
  source(file)
}

```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## load data
ctTable <- dataLoadT1D()

## calculate log2Ex, reformat ctTable, and normalize values
ctNorm <- cleanCt(ctTable, summaryOutput=T, cumExpCutoff = F, normGene = "none")
```

```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## Keep only Tetramer cells
ctNorm <- ctNorm[ctNorm$markerType == "Tetramer", ]
cellsTotal <- nrow(ctNorm)
cellsWithNoExp <- nrow(ctNorm[which(rowSums(ctNorm[,9:ncol(ctNorm)], na.rm=T) == 0),])
  
ctNorm <- ctNorm[which(rowSums(ctNorm[,9:ncol(ctNorm)], na.rm=T) > 0),]
  
cat(paste("No expression detected in ", cellsWithNoExp, "/", cellsTotal, " Tetramer cells", sep=""))
```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## cluster and filter
ctClust <- clusterFilter(ctNorm, testK = T, numCenters = 3, plotHeatmap=T, plotClustOnly=F,
                          heatmapFactor = "kmeans.cluster", heatmapColorBy = c("marker", "cohort"),
                          heatmapcohortLabel = "T1D Samples",
                          fisherTests = c("cohort", "marker"),
                          # fisherTests = NULL,
                          cumulativeExpHist = T, filterClusters = T, clustersToRemove = c(2, 3))
```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
# cluster again to check performance
ctClust <- subset(ctClust, select = -kmeans.cluster)
ctClust <- clusterFilter(ctClust, testK = T, numCenters = 3, plotHeatmap=T, plotClustOnly=F,
                          heatmapFactor = "kmeans.cluster", heatmapColorBy = c("marker", "cohort"),
                          heatmapcohortLabel = "T1D Samples",
                          fisherTests = c("cohort", "marker"),
                          # fisherTests = NULL,
                          cumulativeExpHist = T, filterClusters = F, clustersToRemove = NULL)

```

```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
#### UMAP reports ####
plotUMAP(ctClust, colorby = c("kmeans.cluster", "cohort", "marker"))
```

```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
#### t-sne reports ####
plotTSNE(ctClust, colorby = c("kmeans.cluster", "cohort", "marker"))
```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
#### violins ####

## Differentially expressed genes between cluster
violinPlot(ctGenes=ctClust,
           byFactor="kmeans.cluster",
           factorOrder=c(1:3),
           groupLabel="clusters",
           extraLabel="for human samples",
           dotSize = 1.5,
           dotAlpha = 0.3)

##  Differentially expressed genes between patients
# violinPlot(ctGenes=ctClust,
#            byFactor="probe",
#            factorOrder=c("RAD1","RAD2","RAD3","RAD4","RAD5","RAD6","TEY3","TEY6","TEY8","TEY14",
#                          "TNET1","TNET2","TNET3","TNET4","Healthy"),
#            groupLabel="patients",
#            extraLabel="for human samples",
#            dotSize = 1.5,
#            dotAlpha = 0.3)

##  Differentially expressed genes between cohorts
violinPlot(ctGenes=ctClust,
           byFactor="cohort",
           factorOrder=c("Child","Adult","Risk","Healthy"),
           groupLabel="Cohorts",
           extraLabel="for human samples",
           dotSize = 1.5,
           dotAlpha = 0.3)

##  Differentially expressed genes between types of markers
# violinPlot(ctGenes=ctClust,
#            byFactor="markerType",
#            factorOrder=c("Tetramer", "Surface", "Bulk_CD4+"),
#            groupLabel="Types of Markers",
#            extraLabel="for human samples",
#            dotSize = 1.5,
#            dotAlpha = 0.3)

##  Differentially expressed genes between markers
violinPlot(ctGenes=ctClust,
           byFactor="marker",
           factorOrder=c(#"PD1-/ICOS-", "PD1+/ICOS+", "PD1+/ICOS-", "ICOS+/PD1-", 
                         #"PD1-/CXCR3-","PD1+/CXCR3+", "CXCR3+/PD1-",
                         "12-20", "13-21", "CP11", "CP13", "CP18","Alt1-9", "CLIP"), 
                         #"Bulk_CD4+"),
           groupLabel="Markers",
           extraLabel="for human samples",
           dotSize = 1.5,
           dotAlpha = 0.3)



#### bottom ####
```




