---
title: "T1D_specific_analysis"
output:
  pdf_document: default
  html_document: default
---

```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
knitr::opts_knit$set(global.par = TRUE)
```

```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
library(plyr)
library(ggplot2)
library(RColorBrewer)
library(reshape2)
library(gplots)
library(gtools)
library(stats)
library(lattice)
library(latticeExtra)
library(grid)
library(gridExtra)
library(wesanderson)
library(Rtsne)
library(tidyverse)
library(pheatmap)
```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}

## set baseDir if Knitting with RStudio button
baseDir <- "~/Desktop/Su Lab/single_cell_T1D/"

## sets path if run from runAnalysis.R
#currentFile <- rstudioapi::getActiveDocumentContext()$path
#baseDir <- gsub("single_cell_T1D/.*", "single_cell_T1D/", currentFile)

#### source function scripts ####
funcDir <- paste(baseDir, "src/functions/", sep="")
funcFiles <- c("dataLoadT1D.R", 
               "cleanCt.R", 
               "heatmap2_custom.R",
               "heatmap.3.R",
               "clusterFilter.R",
               "tableBarPlots.R",
               "clusterReport.R",
               "plotTSNE.R",
               "geneExpressHistogram.R",
               "compareTopGenes.R",
               "SpecificHeatMap.R")
funcFiles <- paste(funcDir, funcFiles, sep="")
for(file in funcFiles){
  source(file)
}

```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## load data
ctTable <- dataLoadT1D()

## calculate log2Ex, reformat ctTable, and normalize values
ctNorm <- cleanCt(ctTable, summaryOutput=T, cumExpCutoff = F, normGene = "none")
```


```{r eval=FALSE, fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
#ctNorm[is.na(ctNorm)] <- 0 
```


### For all Tetramer cells
```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## Select all cell with Tetramer Markers
ctSelect <- ctNorm
all_Tetramer_all <- ctSelect[ctSelect$age == "12-20", ]
for (i in c("13-21", "CP11", "CP13", "CP18", "Alt1-9")){
  all_Tetramer_all <- rbind(all_Tetramer_all, ctSelect[ctSelect$age == i, ])
}
## Selecvt only Child and Risk corhorts for analysis
all_Tetramer <- all_Tetramer_all[all_Tetramer_all$cellSource == "Child", ]
all_Tetramer <- rbind(all_Tetramer, all_Tetramer_all[all_Tetramer_all$cellSource == "Risk", ])

## Plot number of gene expressed distribution for all selected cells and get top 20 expressed genes
top_20Tetramer <- geneExpressHistogram(all_Tetramer, num_top = 20)

## Plot the heatmap for top_20 tetramer genes on all_tetramer cells
topT_T_df <- all_Tetramer[top_20Tetramer]
pheatmap(t(topT_T_df), fontsize = 28)
```


### For all PD1+/ICOS+ cells
```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## Select all PD1+/ICOS+ cells
ctSelect <- ctNorm
all_PD1ICOS_all <- ctSelect[ctSelect$age == "PD1+/ICOS+", ]
## Selecvt only Child and Risk corhorts for analysis
all_PD1ICOS <- all_PD1ICOS_all[all_PD1ICOS_all$cellSource == "Child", ]
all_PD1ICOS <- rbind(all_PD1ICOS, all_PD1ICOS_all[all_PD1ICOS_all$cellSource == "Risk", ])

## Plot number of gene expressed distribution for all selected cells and get top 20 expressed genes
top_20PD1ICOS <- geneExpressHistogram(all_PD1ICOS, num_top = 20)

## Plot the heatmap for top_20 PD1ICOS genes on all_PD1ICOS cells
topPI_PI_df <- all_PD1ICOS[top_20PD1ICOS]
pheatmap(t(topPI_PI_df), fontsize = 28)
```


### Cross comparison heat map: PD1+/ICOS+ cells with top_20 Tetramer expressing genes
```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## Cross compare the top expressed genes
topT_PI_df <- all_PD1ICOS[top_20Tetramer]
pheatmap(t(topT_PI_df), fontsize = 28)
```


### Cross comparison heat map: Tetramer cells with top_20 PD1+/ICOS+ expressing genes
```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## Cross compare the top expressed genes
topPI_T_df <- all_Tetramer[top_20PD1ICOS]
pheatmap(t(topPI_T_df), fontsize = 28)
```


### Tetramer cells with Low/High expression level analysis and Cross Comparision
```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## Separated analysis for cell with low and high expression level
SpecificHeatMap(all_Tetramer, low_Cut = 7, high_cut = 27, num_top = 20, all_PD1ICOS, top_20PD1ICOS)
```


```{r eval=FALSE, fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## cluster and filter out low expression cells
ctClust <- clusterFilter(ctNorm, testK = T, numCenters = 2, plotHeatmap=T, plotClustOnly=F,
                          heatmapFactor = "kmeans.cluster", heatmapColorBy = c("age","probe", "soucre"),
                          heatmapTissueLabel = "T1D Samples",
                          fisherTests = c("probe", "tissue", "age"),
                          # fisherTests = NULL,
                          cumulativeExpHist = T, filterClusters = T, clustersToRemove = c(2))
```


```{r eval=FALSE, fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## Select PD1+/ICOS+ cells from RAD and TNET 
ctSelect <- ctClust
ctSelect_RAD <- ctSelect[grepl("RAD", ctSelect$probe, fixed=TRUE), ]
ctSelect_TNET <- ctSelect[grepl("TNET", ctSelect$probe, fixed=TRUE), ]
ctSelect = rbind(ctSelect_RAD, ctSelect_TNET)
ctSelect <- ctSelect[ctSelect$age == "PD1+/ICOS+", ]

#### t-sne reports ####
plotTSNE(ctSelect, colorby = c("patient", "cohort"))
```


```{r eval=FALSE, fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## Select all cell with Tetramer Markers
ctSelect <- ctClust
ctSelect_bind <- ctSelect[ctSelect$age == "12-20", ]
for (i in c("13-21", "CP11", "CP13", "CP18")){
  ctSelect_bind <- rbind(ctSelect_bind, ctSelect[ctSelect$age == i, ])
}

#### t-sne reports ####
plotTSNE(ctSelect_bind, colorby = c("patient", "cohort", "marker"))
```


```{r eval=FALSE, fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## Select all cell with Tetramer Markers
ctSelect <- ctClust
# ctSelect_bind <- ctSelect[ctSelect$age == "12-20", ]
# for (i in c("13-21", "CP11", "CP13", "CP18")){
#  ctSelect_bind <- rbind(ctSelect_bind, ctSelect[ctSelect$age == i, ])
# }
ctSelect_bind <- rbind(ctSelect_bind, ctSelect[ctSelect$age == "PD1+/ICOS+", ])

#### t-sne reports ####
plotTSNE(ctSelect_bind, colorby = c("Tpype_marker", "cohort", "marker"))
```







